version: '3.8'

services:
  spring-boot-app:
    build: .
    environment:
      - JDBC_DATABASE_URL=${DATABASE_URL}
      - JDBC_DATABASE_USERNAME=${DATABASE_USERNAME}
      - JDBC_DATABASE_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "443:8080"
